name: Build bpftools archives

on: [push, pull_request]

jobs:
  build_bpftools:
    name: Build bpftools archive
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        env:
        - NAME: arm64
          NDK_ARCH: arm64
          TARGET: bpftools
          OUTPUT: bpftools-arm64.tar.gz
        - NAME: x86_64
          NDK_ARCH: x86_64
          TARGET: bpftools
          OUTPUT: bpftools-x86_64.tar.gz
        - NAME: arm64-min
          NDK_ARCH: arm64
          TARGET: bpftools-min
          OUTPUT: bpftools-min-arm64.tar.gz
        - NAME: x86_64-min
          NDK_ARCH: x86_64
          TARGET: bpftools-min
          OUTPUT: bpftools-min-x86_64.tar.gz
        - NAME: armv7-min-static
          NDK_ARCH: armv7
          STATIC_LINKING: true
          LLVM_BPF_ONLY: true
          TARGET: bpftools-min
          OUTPUT: bpftools-min-armv7.tar.gz
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: sudo ./scripts/jammy-install-deps.sh
    - name: Setup ndk
      run: ./scripts/download-ndk.sh
    - name: Build
      env: ${{matrix.env}}
      run: make $TARGET NDK_PATH=`pwd`/android-ndk-r23b NDK_ARCH=$NDK_ARCH STATIC_LINKING=$STATIC_LINKING LLVM_BPF_ONLY=$LLVM_BPF_ONLY
    - uses: actions/upload-artifact@v3
      with:
        name: bpftools
        path: ${{ matrix.env['OUTPUT'] }}
